Repository UBC-MDS/pymlviz, pull requests merged in 2020-03, with the labels that each got.

#24 Elaborating on the description
  README.md
Labels: documentation

#37 Model comparison function with test cases
  .gitignore
  poetry.lock
  pymlviz/model_comparison_table.py
  pymlviz/pymlviz.py
  pyproject.toml
  tests/test_model_comparison_table.py
Labels: function-dev

#34 Confusion matrix function and test development, need to check input t…
  poetry.lock
  pymlviz/plot_confusion_m.py
  pymlviz/pymlviz.py
  pyproject.toml
  tests/test_confusion_m.py
Labels: function-dev

#39 Anasm 17 patch 1
  README.md
Labels: documentation

#41 added different OS
  .github/workflows/build.yml
Labels: documentation

#50 fixed stylecheck for confusion matrix function
  pymlviz/plot_confusion_m.py
  tests/test_confusion_m.py
Labels: documentation

#53 deleted new line
  pymlviz/__init__.py
Labels: function-dev

#52 trigger actions
  README.md
Labels: function-dev

#55 fix: Github build file error line
  .github/workflows/build.yml
Labels: bug

#59 fix: model comparison table function fix for mac OS python 3.7
  tests/test_model_comparison_table.py
Labels: bug

#60 fix: release build file fix
  .github/workflows/release.yml
Labels: bug

#62 updated docstring
  pymlviz/plot_confusion_m.py
Labels: documentation

#64 Model comp test fix
  tests/test_model_comparison_table.py
Labels: bug

#69 fix: yaml file fix added git username and repo
  .github/workflows/release.yml
Labels: bug

#71 Updated usage
  docs/usage.rst
Labels: documentation

#72 Updated Confusion Matrix Usage in Readme
  README.md
Labels: documentation

#77 fix: requirements updated
  poetry.lock
  pymlviz/__init__.py
  pyproject.toml
Labels: bug

#78 fix: updated dependencies
  poetry.lock
  pyproject.toml
Labels: bug

#80 feat: updated requirements in readme
  README.md
Labels: documentation

#85 closes issue #84
  pymlviz/model_comparison_table.py
Labels: documentation

#87 Added example to readme
  README.md
Labels: documentation

#91 Fix dependencies
  README.md
Labels: documentation

#90 fixed readthedocs page closes issue 89
  docs/source/modules.rst
  docs/source/pymlviz.rst
  pymlviz/model_comparison_table.py
  pymlviz/plot_confusion_m.py
  pymlviz/plot_roc.py
Labels: documentation

#93 Fixed readthedocs
  README.md
Labels: documentation

#94 Updated Docstring and readme to include dummy data for confusion matr…
  README.md
  pymlviz/plot_confusion_m.py
Labels: documentation
