Repository UBC-MDS/pymlviz, pull requests merged in 2020-02, with the labels that each got.

#12 fixing up
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation

#13 new initialization with python function for model dev
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  .readthedocs.yml
  CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  LICENSE
  README.md
  docs/Makefile
  docs/conf.py
  docs/contributing.rst
  docs/contributors.rst
  docs/index.rst
  docs/installation.rst
  docs/make.bat
  docs/readme.rst
  docs/usage.rst
  pymlviz/__init__.py
  pymlviz/pymlviz.py
  pyproject.toml
  tests/__init__.py
  tests/test_pymlviz.py
Labels: documentation, function-dev

#14 added description for scoring param
  pymlviz/pymlviz.py
Labels: function-dev

#15 Added confusion matrix function definition as well as updated document…
  CONTRIBUTORS.md
  pymlviz/pymlviz.py
Labels: function-dev
